apiVersion: v1
kind: Service
metadata:
  name: draco
spec:
  ports:
  - name: jupyter
    port: 8888
    nodePort: 30088
  selector:
    app: draco
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: draco
spec:
  selector:
    matchLabels:
      app: draco
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: draco
    spec:
      containers:
      - image: signalsdev/draco:latest
        name: draco
        ports:
        - containerPort: 8888
          name: jupyter
